### ISSUE TITLE
HomeConfig 홈 큐레이션(오늘만 할인, 매거진)

### ISSUE THREAD

**Issue by hoona1011** [onulstore/Onulstore-FE-adimin#7]
## Description
홈 큐레이션 설정 페이지 기능을 구현합니다

## Todo List

- [x] 홈, 큐레이션 설정 페이지
- [x] 오늘만 할인 아이템 설정 페이지(테이블) (API 없음)
- [x] 오늘만 할인 아이템 상세설정 모달(API 없음)
- [x] 매거진 설정 페이지(테이블)
- [x] 매거진 등록, 수정용 폼
- [x] 매거진 등록, 수정 페이지
- [x] 매거진 아이템 선택 모달 (아이템 검색 API가 제대로 작동하지 않습니다)
